Run pyinstaller packaging/build.spec --noconfirm
568 INFO: PyInstaller: 6.9.0, contrib hooks: 2026.6
568 INFO: Python: 3.11.9
578 INFO: Platform: Windows-10-10.0.26100-SP0
578 INFO: Python environment: C:\hostedtoolcache\windows\Python\3.11.9\x64
586 INFO: Module search paths (PYTHONPATH):
['C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\Scripts\\pyinstaller.exe',
 'C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\python311.zip',
 'C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\DLLs',
 'C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\Lib',
 'C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64',
 'C:\\hostedtoolcache\\windows\\Python\\3.11.9\\x64\\Lib\\site-packages',
 'D:\\a\\FingerPrint-Native\\FingerPrint-Native',
 'D:\\a\\FingerPrint-Native\\FingerPrint-Native']
837 INFO: Appending 'datas' from .spec
Unable to find 'D:\\a\\FingerPrint-Native\\FingerPrint-Native\\ui\\styles\\theme.qss' when adding binary and data files.
Error: Process completed with exit code 1.
